// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfSU2QAJlMjk3EcqgfKCwdnF754o4ZPc',
    appId: '1:487155350009:web:f8fd2ec4069b6d2c6c6528',
    messagingSenderId: '487155350009',
    projectId: 'hydracal',
    authDomain: 'hydracal.firebaseapp.com',
    storageBucket: 'hydracal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufRrM_MaGlTcNIGd6WR_hbmk83qwPTX4',
    appId: '1:487155350009:android:62b17cade373663d6c6528',
    messagingSenderId: '487155350009',
    projectId: 'hydracal',
    storageBucket: 'hydracal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5_cy8leHnZIS4U2Zn0BCb-KyolzD7i0',
    appId: '1:487155350009:ios:603a4f4286e7cff76c6528',
    messagingSenderId: '487155350009',
    projectId: 'hydracal',
    storageBucket: 'hydracal.firebasestorage.app',
    iosBundleId: 'com.example.mobappGpprojectHydracalFoodscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl5_cy8leHnZIS4U2Zn0BCb-KyolzD7i0',
    appId: '1:487155350009:ios:603a4f4286e7cff76c6528',
    messagingSenderId: '487155350009',
    projectId: 'hydracal',
    storageBucket: 'hydracal.firebasestorage.app',
    iosBundleId: 'com.example.mobappGpprojectHydracalFoodscanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmfSU2QAJlMjk3EcqgfKCwdnF754o4ZPc',
    appId: '1:487155350009:web:0b41e7d073e552046c6528',
    messagingSenderId: '487155350009',
    projectId: 'hydracal',
    authDomain: 'hydracal.firebaseapp.com',
    storageBucket: 'hydracal.firebasestorage.app',
  );
}
